### ISSUE TITLE
Docs: Feedback for 5.3.0 Release Notes

### ISSUE THREAD

**Issue by padmajan87** [hazelcast/hz-docs#943]
Hi Team,
   Is there any rule about the mongo java driver version to be used with this release?

Hazelcast 4.2.8 was running fine with mongo-java-driver 3.12.14. But when I upgraded hazlecast version to 5.3.6 I am getting following error

java.land.NoSuchMEthodError: 'java.lang.Integer: com.mongodb.ConnectionString.getThreadAllowedTpBlockForConnectionMultiplier()

Thanks,
Padmajan V

**Comment by Serdaro** [comment]
@padmajan87 , was this also fixed when you removed the hidden 5.3.2 installation on your local?

**Comment by padmajan87** [comment]
@Serdaro I think I resolved it by using mongodb-driver-sync.
